import React from "react";
import Container from 'muicss/lib/react/container';
import FontAwesome from 'react-fontawesome';
// import Image from 'react-native';




const hrList ={
	float: "left",
	textDecoration: 'none',
}

const listStyling = {
    listStyleType: 'none',
    margin:'0',
    padding: '0px',
    overflow: 'hidden',
    display:'block',
    textAlign: 'center',
}



class Resume extends React.Component {
  render() {
    return (
    	<div>
            <div class="card-header">
    			<div class="card-header-title is-centered" align="center">
                    <h2>PATRICK CARLSON</h2>
                </div>
            </div>
            <div class="card-content">
    			<img height="240" width="240" src={require("./images/patrick.jpg")} alt="My wife and me" />
                <p>
                <b>Education:</b><br />
                North Carolina State University, Raleigh, NC <br />
                B.S. in Computer Science, (2012-Present)<br />
                <br />
                <b>Skills:</b><br />
                Programming Languages:<br />
                • Java, Python, C, HTML, CSS, JavaScript, JS Frameworks(React, Angular), Django
                <br />
                Operating Systems:<br />
                • Windows ( 8, 7, Vista, XP, DOS) RHEL, Fedora, Ubuntu<br />
                Database Systems: <br />
                • SQL, MySQL, MongoDB<br /><br />
                <b>Certifications:</b><br />
                • Google Cloud Platform OnBoard - August 2017<br />
                <br />
                <b>Honors / Awards</b><br />
                Eagle Scout – Boy Scouts of America
                </p>
                <p>
                <b>Technical Experience:</b><br />
                Snowshoe Hare Recognition Testing Program, Individual Undergrad Research<br />
                Programmer/Designer, May 2014 – August 2014<br />
                • Design a program to test human reaction speed of Hare identification under various circumstances.<br />
                <br />
                <b>Work Experience:</b><br />
                Red Hat Software, Raleigh, NC<br />
                Technical Support Intern May 2015 – Present<br />
                • Testing and debugging of various pieces of code generated by manager and associated interns.<br />
                • Worked on a development team to create Web Tools on our own created platform to enhance<br />
                engagement between engineering and support teams within Red Hat. Used Angular JS, HTML, CSS<br />
                Python and MongoDB to accomplish this.<br />
                <br />
                <b>Leadership Experience</b><br />
                eSports at North Carolina State University<br />
                Founding Member, August 2013 – May 2014<br />
                • Planned and ran Spring 2014 LAN with 30 attendees<br />
                President, May 2014 – August 2015<br />
                • Established relationship with Texas eSports Association to join as active Chapter.<br />
                • Planned and ran two LANS and tournaments both with over 150 attendees each with attendees from<br />
                across the state.<br />
                </p>
            </div>
      </div>
    );
  }
}
 
export default Resume